chore(pre-commit): use error handler function to abort commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,7 +3,10 @@
 # Description: Pre-commit hook for hot-plate.
 # =========================================================================== #
 
-if ! make lint; then
-	printf "Commit aborted: 'make lint' failed.\n"
+die() {
+	local msg="$1"
+	printf "Commit aborted: %s\n" "$msg" >&2
 	exit 1
-fi
+}
+
+! make lint && die "'make lint' failed."
