(commit): remove start of commit-msg hook terminal output, format error message for pre-commit hook similar to commit-msg errors

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -4,6 +4,6 @@
 # =========================================================================== #
 
 if ! make lint; then
-	printf "Commit aborted: 'make lint' failed.\n" >&2
+	printf "'make lint' failed. Aborting commit.\n" >&2
 	exit 1
 fi
